### ISSUE TITLE
Group Image and Description

### ISSUE THREAD

**Issue by cyouh95** [deveddev/Tea-Cozy#1]
Group each image/description pair inside a `div` container. Then, specify `display: block;` for the `img` and `h4` tags so they will be stacked.

HTML:
```html
<div class="item">
    <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-berryblitz.jpg">
    <h4>Fall Berry Blitz Tea</h4>
</div>
```

CSS:
```css
.item img {
  display: block;
  ...
}

.item span {
  display: block;
  ...
}
```

https://github.com/deveddev/Tea-Cozy/blob/master/Desktop/Codecademy/Tea%20Cozy/index.html#L45-L62
